netbox_vcenter/urls.py
from django.urls import path

from .views import ClusterVCenterDeleteView, ClusterVCenterEditView, VirtualMachineRefresh, VirtualMachineUpdate

urlpatterns = [
    path('clusters/<int:cluster_id>/edit/', ClusterVCenterEditView.as_view(), name='cluster_vcenter_edit'),
    path('clusters/<int:cluster_id>/delete/', ClusterVCenterDeleteView.as_view(), name='cluster_vcenter_delete'),
    path('virtualhosts/<int:virtualmachine_id>/update/<field>/', VirtualMachineUpdate.as_view(),
         name='virtualmachine_update'),
    path('virtualhosts/<int:virtualmachine_id>/refresh/', VirtualMachineRefresh.as_view(),
         name='virtualmachine_refresh'),

    # path('compare/', CompareVCenterView.as_view(), name='compare'),
]

netbox_vcenter/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from netbox_vcenter.validators import HostnameAddressValidator
from virtualization.models import Cluster


class ClusterVCenter(models.Model):
    cluster = models.OneToOneField(
        to=Cluster,
        on_delete=models.CASCADE,
        related_name='vcenter',
    )
    server = models.CharField(
        verbose_name=_('vCenter Server'),
        max_length=64,
        validators=[HostnameAddressValidator()],
    )
    validate_certificate = models.BooleanField(
        verbose_name=_('validate certificate'),
        default=True,
    )
    username = models.CharField(
        verbose_name=_('username'),
        max_length=64,
    )
    password = models.CharField(
        verbose_name=_('password'),
        max_length=64,
    )

    class Meta:
        verbose_name = _('vCenter configuration')
        verbose_name_plural = _('vCenter configurations')

    def __str__(self):
        return self.cluster.name

    def get_absolute_url(self):
        return self.cluster.get_absolute_url()

netbox_vcenter/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from netbox_vcenter.models import ClusterVCenter
from utilities.forms import BootstrapMixin


class ClusterVCenterEditForm(BootstrapMixin, forms.ModelForm):
    new_password = forms.CharField(
        max_length=64,
        label='Password',
        widget=forms.PasswordInput(),
        help_text=_('This password is stored unencrypted in the database. '
                    'Use a read-only account with limited privileges!'),
    )

    class Meta:
        model = ClusterVCenter
        fields = ['server', 'validate_certificate', 'username']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if self.instance and self.instance.password:
            # Hack the password field and make it non-required
            self.fields['new_password'].required = False
            self.fields['new_password'].widget.is_required = False
            if 'required' in self.fields['new_password'].widget.attrs:
                del self.fields['new_password'].widget.attrs['required']
            self.fields['new_password'].widget.attrs['placeholder'] = 'current password hidden'

    def _post_clean(self):
        # Update the password if it is provided
        if self.cleaned_data['new_password']:
            self.instance.password = self.cleaned_data['new_password']

        return super()._post_clean()

netbox_vcenter/views.py
import logging
import time
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import Http404, HttpResponseBadRequest
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import View
from rq.job import Job

from netbox_vcenter.background_tasks import refresh_virtual_machines
from netbox_vcenter.forms import ClusterVCenterEditForm
from netbox_vcenter.models import ClusterVCenter
from utilities.views import GetReturnURLMixin, ObjectDeleteView, ObjectEditView
from virtualization.models import Cluster, VirtualMachine

logger = logging.getLogger('netbox_vcenter')


class ClusterVCenterObjectMixin:
    def get_object(self, kwargs):
        if 'cluster_id' not in kwargs:
            raise Http404

        cluster = get_object_or_404(Cluster, pk=kwargs['cluster_id'])

        try:
            return ClusterVCenter.objects.get(cluster=cluster)
        except ClusterVCenter.DoesNotExist:
            return ClusterVCenter(cluster=cluster)


class ClusterVCenterEditView(PermissionRequiredMixin, ClusterVCenterObjectMixin, ObjectEditView):
    permission_required = 'change_clustervcenter'
    model = ClusterVCenter
    model_form = ClusterVCenterEditForm


class ClusterVCenterDeleteView(PermissionRequiredMixin, ClusterVCenterObjectMixin, ObjectDeleteView):
    permission_required = 'delete_clustervcenter'
    model = ClusterVCenter


class VirtualMachineRefresh(PermissionRequiredMixin, GetReturnURLMixin, View):
    permission_required = 'view_virtualmachine'

    def post(self, request, virtualmachine_id):
        config = settings.PLUGINS_CONFIG['netbox_vcenter']

        vm = get_object_or_404(VirtualMachine, pk=virtualmachine_id)
        vcenter = vm.cluster.vcenter

        logger.info("Forcing background task to retrieve VMs from {}".format(vcenter.server))
        job = refresh_virtual_machines.delay(vcenter=vcenter, force=True)  # type: Job

        delay = 0.2
        max_wait = config['REFRESH_WAIT']
        max_loops = max_wait / delay
        loops = 0
        while job.is_queued or job.is_started:
            if loops > max_loops:
                break

            time.sleep(delay)
            loops += 1

        return redirect(self.get_return_url(request, vm))


class VirtualMachineUpdate(PermissionRequiredMixin, GetReturnURLMixin, View):
    permission_required = 'change_virtualmachine'

    def post(self, request, virtualmachine_id, field):
        if field not in ['vcpus', 'memory', 'disk']:
            raise Http404

        if field not in request.POST:
            return HttpResponseBadRequest(f'No value provided for {field}')

        try:
            value = int(request.POST[field])
        except ValueError:
            return HttpResponseBadRequest(f'Value of {field} must be an integer')

        vm = get_object_or_404(VirtualMachine, pk=virtualmachine_id)
        setattr(vm, field, value)
        vm.save()

        messages.info(request, f"Updated {vm._meta.get_field(field).verbose_name} of {vm.name}")

        return redirect(self.get_return_url(request, vm))

# class CompareVCenterView(View):
#     def __init__(self, **kwargs):
#         super().__init__(**kwargs)
#
#         self.content = None
#         self._pgs_cache = {}
#
#     def get(self, request):
#         try:
#             self.content = service_instance.RetrieveContent()
#
#             output = ''
#             vms = self.get_objects_of_type(vim.VirtualMachine)
#             for vm in vms:
#                 output += f'VM {vm.name}\n'
#                 for dev in vm.config.hardware.device:
#                     if isinstance(dev, vim.vm.device.VirtualEthernetCard):
#                         vlan = self.get_nic_vlan(vm, dev)
#                         output += f'  NIC {dev.deviceInfo.label} [{dev.macAddress}] = {vlan}\n'
#
#             return HttpResponse(output, "text/plain")
#         finally:
#             connect.Disconnect(service_instance)
#
#     def get_objects_of_type(self, obj_type):
#         view_mgr = self.content.viewManager.CreateContainerView(self.content.rootFolder,
#                                                                 [obj_type],
#                                                                 True)
#         try:
#             return list(view_mgr.view)
#         finally:
#             view_mgr.Destroy()

netbox_vcenter/templates/netbox_vcenter/cluster/vcenter_info.html
{% if perms.netbox_vcenter.view_clustervcenter %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong>vCenter</strong>
        </div>
        {% if object.vcenter %}
            <table class="table table-hover panel-body attr-table">
                <tbody>
                    <tr>
                        <td>vCenter Server</td>
                        <td>
                            <a href="https://{{ object.vcenter.server }}/ui/"
                               target="_blank">{{ object.vcenter.server }}</a>

                            {% if not object.vcenter.validate_certificate %}
                                <span class="text-muted">(insecure)</span>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Username</td>
                        <td>
                            {{ object.vcenter.username }}
                        </td>
                    </tr>
                </tbody>
            </table>
        {% else %}
            <div class="panel-body">
                <span class="text-muted">No vCenter settings configured</span>
            </div>
        {% endif %}
        <div class="panel-footer noprint">
            {% if object.vcenter %}
                {% if perms.netbox_vcenter.change_clustervcenter %}
                    <div class="pull-right">
                        <a href="{% url 'plugins:netbox_vcenter:cluster_vcenter_edit' cluster_id=object.id %}"
                           class="btn btn-warning btn-xs">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                            Edit vCenter settings
                        </a>
                    </div>
                {% endif %}

                {% if perms.netbox_vcenter.delete_clustervcenter %}
                    <a href="{% url 'plugins:netbox_vcenter:cluster_vcenter_delete' cluster_id=object.id %}?return_url={{ request.path }}"
                       class="btn btn-danger btn-xs">
                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        Delete vCenter settings
                    </a>
                {% endif %}
            {% else %}
                {% if perms.netbox_vcenter.add_clustervcenter %}
                    <div class="pull-right">
                        <a href="{% url 'plugins:netbox_vcenter:cluster_vcenter_edit' cluster_id=object.id %}"
                           class="btn btn-primary btn-xs">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                            Add vCenter settings
                        </a>
                    </div>
                {% endif %}
            {% endif %}

            <br style="clear: both">
        </div>
    </div>
{% endif %}

netbox_vcenter/templates/netbox_vcenter/virtualmachine/vcenter_refresh.html
{% if perms.virtualization.view_virtualmachine %}
    <form method="post" style="display: inline-block">
        {% csrf_token %}

        <button type="submit" name="_edit"
                formaction="{% url 'plugins:netbox_vcenter:virtualmachine_refresh' virtualmachine_id=object.id %}"
                class="btn btn-info">
            <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span> Refresh vCenter Info
        </button>
    </form>
{% endif %}

netbox_vcenter/templates/netbox_vcenter/virtualmachine/vcenter_resources.html
{% load helpers %}

<div class="panel panel-default">
    <div class="panel-heading">
        <strong>vCenter Resources</strong>
        <span class="pull-right text-muted">cached: {{ vcenter_timestamp|date:"DATETIME_FORMAT" }}</span>
    </div>
    <form method="post">
        {% csrf_token %}

        <table class="table table-hover panel-body attr-table">
            <tr>
                <th></th>
                <th>NetBox</th>
                <th>vCenter</th>
                <th></th>
            </tr>
            <tr>
                <td><i class="fa fa-tachometer"></i> Virtual CPUs</td>
                <td>{{ object.vcpus|placeholder }}</td>
                <td>
                    {% if object.vcpus != vcenter_resources.vcpus %}
                        <span class="text-danger">
                           {{ vcenter_resources.vcpus|placeholder }}
                       </span>
                    {% else %}
                        {{ vcenter_resources.vcpus|placeholder }}
                    {% endif %}
                </td>
                <td style="width: 25%">
                    {% if vcenter_resources.vcpus and object.vcpus != vcenter_resources.vcpus %}
                        {% if perms.virtualization.change_virtualmachine %}
                            <div class="pull-right">
                                <input type="hidden" name="vcpus" value="{{ vcenter_resources.vcpus }}">
                                <button type="submit" name="_edit"
                                        formaction="{% url 'plugins:netbox_vcenter:virtualmachine_update' virtualmachine_id=object.id field='vcpus' %}"
                                        class="btn btn-warning btn-xs">
                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Update NetBox
                                </button>
                            </div>
                        {% endif %}
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td><i class="fa fa-microchip"></i> Memory</td>
                <td>
                    {% if object.memory %}
                        {{ object.memory }} MB
                    {% else %}
                        <span class="text-muted">&mdash;</span>
                    {% endif %}
                </td>
                <td>
                    {% if vcenter_resources.memory %}
                        {% if object.memory != vcenter_resources.memory %}
                            <span class="text-danger">
                               {{ vcenter_resources.memory }} MB
                           </span>
                        {% else %}
                            {{ vcenter_resources.memory }} MB
                        {% endif %}
                    {% else %}
                        <span class="text-muted">&mdash;</span>
                    {% endif %}
                </td>
                <td>
                    {% if vcenter_resources.memory and object.memory != vcenter_resources.memory %}
                        {% if perms.virtualization.change_virtualmachine %}
                            <div class="pull-right">
                                <input type="hidden" name="memory" value="{{ vcenter_resources.memory }}">
                                <button type="submit" name="_edit"
                                        formaction="{% url 'plugins:netbox_vcenter:virtualmachine_update' virtualmachine_id=object.id field='memory' %}"
                                        class="btn btn-warning btn-xs">
                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Update NetBox
                                </button>
                            </div>
                        {% endif %}
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td><i class="fa fa-hdd-o"></i> Disk Space</td>
                <td>
                    {% if object.disk %}
                        {{ object.disk }} GB
                    {% else %}
                        <span class="text-muted">&mdash;</span>
                    {% endif %}
                </td>
                <td>
                    {% if vcenter_resources.disk %}
                        {% if object.disk != vcenter_resources.disk %}
                            <span class="text-danger">
                                {{ vcenter_resources.disk }} GB
                            </span>
                        {% else %}
                            {{ vcenter_resources.disk }} GB
                        {% endif %}
                    {% else %}
                        <span class="text-muted">&mdash;</span>
                    {% endif %}
                </td>
                <td>
                    {% if vcenter_resources.disk and object.disk != vcenter_resources.disk %}
                        {% if perms.virtualization.change_virtualmachine %}
                            <div class="pull-right">
                                <input type="hidden" name="disk" value="{{ vcenter_resources.disk }}">
                                <button type="submit" name="_edit"
                                        formaction="{% url 'plugins:netbox_vcenter:virtualmachine_update' virtualmachine_id=object.id field='disk' %}"
                                        class="btn btn-warning btn-xs">
                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Update NetBox
                                </button>
                            </div>
                        {% endif %}
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td><i class="fa fa-hdd-o"></i> Network interfaces</td>
                <td>
                    {{ object.interfaces.all|length }}
                </td>
                <td>
                    {% if object.interfaces.all|length != vcenter_resources.nics|length %}
                        <span class="text-danger">
                            {{ vcenter_resources.nics|length }}
                        </span>
                    {% else %}
                        {{ vcenter_resources.nics|length }}
                    {% endif %}
                </td>
                <td></td>
            </tr>
        </table>
    </form>
</div>

<script type="application/javascript">
    document.addEventListener("DOMContentLoaded", function () {
        /*
         * VERY ugly hack: hide the original Resources panel and put new panel in its place
         * If this doesn't work we just have two Resource panels, so not too bad…
         */
        const old_panel = document.evaluate("." +
            "//div[contains(concat(' ',normalize-space(@class),' '),' panel ')]" +
            "/div[contains(concat(' ',normalize-space(@class),' '),' panel-heading ')]" +
            "/*[text() = 'Resources']" +
            "/../..",
            document.body,
            null,
            XPathResult.FIRST_ORDERED_NODE_TYPE
        ).singleNodeValue;

        const new_panel = document.evaluate("." +
            "//div[contains(concat(' ',normalize-space(@class),' '),' panel ')]" +
            "/div[contains(concat(' ',normalize-space(@class),' '),' panel-heading ')]" +
            "/*[text() = 'vCenter Resources']" +
            "/../..",
            document.body,
            null,
            XPathResult.FIRST_ORDERED_NODE_TYPE
        ).singleNodeValue;

        if (old_panel) {
            old_panel.style.display = 'none';
            if (new_panel) {
                old_panel.parentNode.insertBefore(new_panel, old_panel.nextSibling);
            }
        }

        /*
         * VERY ugly hack 2: add power state to the status field
         * If this doesn't work we just don't show it
         */
        const vm_panel = document.evaluate("." +
            "//div[contains(concat(' ',normalize-space(@class),' '),' panel ')]" +
            "/div[contains(concat(' ',normalize-space(@class),' '),' panel-heading ')]" +
            "/*[text() = 'Virtual Machine']" +
            "/../..",
            document.body,
            null,
            XPathResult.FIRST_ORDERED_NODE_TYPE
        ).singleNodeValue;

        if (vm_panel) {
            const status = document.evaluate("." +
                "//td[text() = 'Status']" +
                "/following-sibling::td",
                vm_panel,
                null,
                XPathResult.FIRST_ORDERED_NODE_TYPE
            ).singleNodeValue;

            if (status) {
                {% if vcenter_resources.powered_on is True %}
                    status.innerHTML += '<span class="label label-success">Powered on</span>'
                {% elif vcenter_resources.powered_on is False %}
                    status.innerHTML += '<span class="label label-danger">Powered off</span>'
                {% endif %}
            }
        }
    });
</script>